name: my_flutter_application
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^6.0.0
  palette_generator: ^0.3.3+2
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  animate_do: ^2.0.0
  flutter_verification_code: ^1.1.0
  flutter_bloc: ^8.0.0
  font_awesome_flutter: ^9.2.0
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/background.jpg
    - assets/images/one.jpg
    - assets/images/two.jpg
    - assets/images/three.jpg
    - assets/images/four.jpg
    - assets/images/starter-image.jpg
    - assets/images/emma.jpg
    - assets/images/emma-1.jpg
    - assets/images/emma-2.jpg
    - assets/images/emma-3.jpg
    - assets/images/ball.png
    - assets/images/player.png
    - assets/images/player_second.png
    - assets/images/player_third.png
    - assets/images/player_four.png
    - assets/images/players.png
    - assets/images/equipes/barca.png
    - assets/images/equipes/bayern.png
    - assets/images/equipes/france.png
    - assets/images/equipes/lyon.png
    - assets/images/equipes/marseille.png
    - assets/images/equipes/background/bayern.jpg
    - assets/images/players/neymar.jpg
    - assets/images/icons/icon_position_player.png
    - assets/images/icons/icon_position.png
    - assets/images/icons/icon_number.png
    - assets/images/icons/icon_losing.png
    - assets/images/icons/icon_goal.png
    - assets/images/icons/icon_soccer_ball.png
    - assets/images/icons/icon_top_soccer.png
    - assets/images/icons/icon_rebound_leader.png
    - assets/images/icons/icon_winning.png
    - assets/images/icons/icon_draw.png
    - assets/images/icons/icon_draw.png
    - assets/images/icons/icon_player.png
    - assets/images/icons/icon_founded.png
    - assets/images/icons/icon_email.png
    - assets/images/icons/icon_request.png
    - assets/images/icons/icon_started.png
    - assets/images/icons/icon_gmail.png
    - assets/images/icons/icon_date.png
    - assets/images/icons/icon_map.png
    - assets/images/icons/icon_flash.png
    - assets/images/icons/icon_password.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montesserat/Montserrat-Black.ttf
        - asset: assets/fonts/montesserat/Montserrat-Bold.ttf
        - asset: assets/fonts/montesserat/Montserrat-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
